from pynput.keyboard import Key

special_chars = {
    Key.space: ' ',
    Key.enter: '\n',
    Key.esc: ' -esc-',
    Key.shift_l: ' -shift L- ',
    Key.shift_r: ' -shift R- ',
    Key.ctrl_l: ' -ctrl L- ',
    Key.ctrl_r: ' -ctrl R- ',
    Key.tab: '    ',
    Key.delete: ' -del- ',
    Key.caps_lock:' -caps_lock- ',
    Key.insert: ' -insert-',
    Key.home: ' -home- ',
    Key.end: ' -end- ',
    Key.page_up: ' -page up- ',
    Key.page_down: ' -page down- ',
    Key.num_lock: ' -num lock- ',
    Key.print_screen: ' -print screen- ',
    Key.scroll_lock: ' -scroll lock- ',
    Key.pause: 'pause',
    Key.alt_l:' -alt L- ',
    Key.alt_r:' -alt R- ',
    Key.alt_gr:' -alt_gr- ',
    Key.media_play_pause:' -play/pause- ',
    Key.media_next:' -next- ',
    Key.media_previous:' -previous- ',
    Key.media_volume_down:' -previous- ',
    Key.media_volume_up: ' -volume up-',
    Key.media_volume_mute: ' -volume mute-',
    Key.up: ' -arrow up-',
    Key.down: ' -arrow down-',
    Key.left: ' -arrow left-',
    Key.right: ' -arrow right-',
    Key.f1: ' -f1- ',
    Key.f2: ' -f2- ',
    Key.f3: ' -f3- ',
    Key.f4: ' -f4- ',
    Key.f5: ' -f5- ',
    Key.f6: ' -f6- ',
    Key.f7: ' -f7- ',
    Key.f8: ' -f8- ',
    Key.f9: ' -f9- ',
    Key.f10: ' -f10- ',
    Key.f11: ' -f11- ',
    Key.f12: ' -f12- ',
}